service: cors-proxy

plugins:
  - serverless-offline
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${env:DOMAIN_NAME}
    basePath: ''
    stage: prod
    createRoute53Record: true
    endpointType: 'regional'

provider:
  name: aws
  runtime: nodejs10.x
  timeout: 120
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    foo: 123

functions:
  lambda:
    name: cors-proxy
    handler: handler.corsProxy
    events:
      - http:
          path: ''
          method: get
          cors: true
